### ISSUE TITLE
Bundler does'nt work on OS X 10.11.2

### ISSUE THREAD

**Issue by dazdaz** [Tomohiro/airplayer#48]
$ git clone git://github.com/Tomohiro/airplayer.git
$ cd airplayer
$ bundle install --deployment

$ exe/airplayer
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- airplayer (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from exe/airplayer:4:in `<main>'

Am I doing something wrong here, I am unable to run airplayer ?  I am running OS X 10.11.2.  If there is an additional step, could you please add it to the documentation.

Cheers!

**Comment by Tomohiro** [comment]
Please try this:

```
$ git clone git://github.com/Tomohiro/airplayer.git
$ cd airplayer
$ bundle install --deployment --binstubs    # --binstubs creates  executable commands to bin/
$ bin/airplayer version
1.1.0
```

I'm going to update this to the README.

**Comment by dazdaz** [comment]
Works perfectly, thank you!
