### ISSUE TITLE
Stream avi format files to the Apple TV via airplayer

### ISSUE THREAD

**Issue by dazdaz** [Tomohiro/airplayer#52]
Is it possible to play .avi format (Audio Video Interleave) files natively via the AppleTV with airplayer without any file format conversion.

If this is not possible then I'm sure that there is a good reason for this and would you please consider adding the reason to the documentation so that it's clear that only mp4 format files can be streamed.

Cheers!

**Comment by tomohiro** [comment]
Not possible, because it is Apple TV's specification.
I've already linked to [AirPlay supported formats](https://developer.apple.com/library/ios/documentation/AudioVideo/Conceptual/AirPlayGuide/PreparingYourMediaforAirPlay/PreparingYourMediaforAirPlay.html) on the README.

Refs #16, #37
